codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "85..90"
  status:
    project:
      default: # This can be anything, but it needs to exist as the name
        target: 90
        threshold: 5%
        base: auto
    patch:
      default:
        target: 90
        threshold: 5%
        base: auto

